[project]
name = "servey"
version = "0.0.0"  # This will be replaced by the release workflow
description = "A better API layer for python"
authors = [
    {name = "Tim O'Farrell", email = "tofarr@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "cryptography~=46.0",
    "injecty~=0.0",
    "json-urley~=1.0",
    "marshy~=5.0",
    "pyjwt~=2.10",
    "python-dateutil~=2.9",
    "schemey~=8.0",
]

[project.urls]
Repository = "https://github.com/tofarr/servey"

[project.optional-dependencies]
dev = [
    "black~=25.11",
    "boto3~=1.42",
    "pytest~=9.0",
    "pytest-cov~=7.0",
    "pytest-xdist~=3.8",
    "pylint~=4.0",
]
server = [
    "starlette~=0.50",
    "strawberry-graphql~=0.287",
    "uvicorn[standard]~=0.38",
    "pygments~=2.19",
    "requests~=2.32",
    "python-multipart~=0.0",
]
scheduler = [
    "celery~=5.6",
]
serverless = [
    "pyyaml~=6.0",
    "ruamel.yaml~=0.18",
    "strawberry-graphql~=0.287",
]
web_page = [
    "Jinja2~=3.1",
]
all = [
    "black~=25.11",
    "boto3~=1.42",
    "pytest~=9.0",
    "pytest-cov~=7.0",
    "pytest-xdist~=3.8",
    "pylint~=4.0",
    "starlette~=0.50",
    "strawberry-graphql~=0.287",
    "uvicorn[standard]~=0.38",
    "pygments~=2.19",
    "requests~=2.32",
    "python-multipart~=0.0",
    "celery~=5.6",
    "pyyaml~=6.0",
    "ruamel.yaml~=0.18",
    "Jinja2~=3.1",
]

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["servey"]

[tool.hatch.build.targets.sdist]
exclude = ["tests*", "servey_main*", "static_site", "examples"]

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "servey/_version.py"

[tool.black]
extend-exclude = "_version.py"

[dependency-groups]
dev = [
    "black>=25.11.0",
    "hatch-vcs>=0.5.0",
    "hatchling>=1.28.0",
]
