
Resources:
  End2EndIndexFn:
    Type: "AWS::CloudFront::Function"
    Properties:
      Name: "End2EndIndexFn"
      AutoPublish: true
      FunctionConfig:
        Comment: "Add index.html when path ends with /"
        Runtime: "cloudfront-js-1.0"
      FunctionCode: |
        function handler(event) {
            var request = event.request;
            var uri = request.uri;

            if (uri.endsWith('/')) {
                request.uri += 'index.html';
            }
            else if (!uri.includes('.')) {
                request.uri += '/index.html';
            }

            return request;
        }
  End2EndDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Enabled: "true"
          DefaultRootObject: /
          # The default caching applies to the default (root) objects, not to images etc...
          DefaultCacheBehavior:
            AllowedMethods:
            - GET
            - HEAD
            MinTTL: "0"
            MaxTTL: "0"
            DefaultTTL: "0"
            TargetOriginId: myS3Origin
            ForwardedValues:
              QueryString: "false"
            ViewerProtocolPolicy: redirect-to-https
            FunctionAssociations:
              - EventType: "viewer-request"
                FunctionARN:
                  Ref: End2EndIndexFn
          # Here we define two behaviours of how we cache responses
          CacheBehaviors:
          - AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            TargetOriginId: myAPIOrigin
            ForwardedValues:
              QueryString: 'true'
              Cookies:
                Forward: all
            ViewerProtocolPolicy: https-only
            MinTTL: "0"
            MaxTTL: "6"
            DefaultTTL: "3"
            PathPattern: actions/*
          # Here we define the API origin
          Origins:
            - DomainName:
               Fn::Join:
                - ""
                - - Ref: ApiGatewayRestApi
                  - ".execute-api.${self:provider.region}.amazonaws.com"
              Id: myAPIOrigin
              OriginPath: /${self:provider.stage}
              CustomOriginConfig:
                OriginProtocolPolicy: https-only
            # Here's the origin from S3...
            - DomainName: ${self:custom.staticBucket}.s3.amazonaws.com
              #OriginPath: /
              ## An identifier for the origin which must be unique within the distribution
              Id: myS3Origin
              # Dont need this because of permissive bucket policy
              S3OriginConfig:
                OriginAccessIdentity:
                  Fn::Join:
                    - ""
                    - - "origin-access-identity/cloudfront/"
                      - Ref: OriginAccessIdentity
