name: Quality

on: push

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.X
        uses: actions/setup-python@v4
        with:
          python-version: "3.X"
      - name: Install black
        run: python -m pip install --upgrade pip black
      - name: black
        run: black . --check

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install pytest code coverage
        run: python -m pip install ".[all]"
      - name: testcoverage
        run: python -m pytest -n auto --cov-report=term-missing --cov=tests --cov=marshy_config_servey --cov=servey --cov-fail-under=98

  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.X
        uses: actions/setup-python@v4
        with:
          python-version: "3.X"
      - name: Install pylint
        run: python -m pip install ".[all]"
      - name: lint
        run: pylint marshy_config_servey servey
